### ISSUE TITLE
Custom Levels fail to be passed into DeployLevel()

### ISSUE THREAD

**Issue by scarabotto** [candeias/django-envcrypto#9]
Hey @candeias I wanted to change the default run-levels by passing a `Enum` class to DeployLevel, but it's throwing me a `DeploymentIsNotAEnum` exception, which happens because the instance effectively is EnumMeta instead of Enum.

I have a test that profiles the wrong behaviour:
```python
# in tests/test_levels.py

class RealDeploymentEnvironments(Enum):
    DEVELOPMENT = 'development'
    STAGING = 'staging'
    PRODUCTION = 'production'

class LevelsDeployLevel(CommonTestCase):
    # ... previous tests

    def test_levels_is_valid_enum_should_not_raise(self):
        """DeployLevel should give back the specified enum."""
        deploy_level = DeployLevel(levels=RealDeploymentEnvironments)
        self.assertEqual(deploy_level.levels, RealDeploymentEnvironments)
        self.assertEqual(deploy_level.levels.DEVELOPMENT.value, 'development')
        self.assertEqual(deploy_level.levels.STAGING.value, 'staging')
        self.assertEqual(deploy_level.levels.PRODUCTION.value, 'production')
```

My suggestion would be to check `issubclass(levels, Enum)` instead of `isinstance(levels, Enum)`. I already have a PR ready if you agree with the proposed fix 😃

**Comment by candeias** [comment]
hi @scarabotto yes, that is the right solution, only checking the subclass (because of multi inheritance). And please do your PR!

**Comment by scarabotto** [comment]
I can't push anything apparently, I'm getting
```
ERROR: Permission to candeias/django-envcrypto.git denied to scarabotto.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
The remotes look ok. Can you double check the permissions please?

**Comment by martimarkov** [comment]
Might be a stupid suggestion but: fork & PR?
—
MM.
